name: sjfz-ucvm-ci

on:
  push:
    branches: [ foofoo ]

jobs:
  sjfz-build-ucvm-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
    - name: set UCVM_SRC_PATH 
      run: echo "UCVM_SRC_PATH=$RUNNER_WORKSPACE/sjfz/ucvm" >> $GITHUB_ENV
    - name: set UCVM_INSTALL_PATH 
      run: echo "UCVM_INSTALL_PATH=$RUNNER_WORKSPACE/sjfz/target" >> $GITHUB_ENV
### build ucvm(main) first 
    - name: get-ucvm 
      uses: actions/checkout@v2
      with: 
        repository: 'SCECcode/UCVM'
##        ref: main
        ref: testMei
        path: ucvm
    - id: build-ucvm
      name: build ucvm
      uses: ./ucvm/.github/actions/build-ucvm-action
      with:
         initiating-repo: 'sjfz'
         target-model: 'sjfz'
         target-branch: 'testMei'
    - name: get-result ${{ steps.build-ucvm.outputs.build-log }}
      run: more ${{ steps.build-ucvm.outputs.build-log }}
      shell: bash
    - name: move stock sjfz away
      run: (rm -rf $RUNNER_WORKSPACE/sjfz/ucvm/work/model/sjfz)
      shell: bash
### build sjfz from github 
    - name: checkout sjfz main
      uses: actions/checkout@v2
      with: 
        path: sjfz
    - name: move it to the right location
      run: (mv sjfz $RUNNER_WORKSPACE/sjfz/ucvm/work/model; pwd; ls)
      shell: bash
    - name: build sjfz as part of ucvm 
      run: (cd $RUNNER_WORKSPACE/sjfz/ucvm/work/model/sjfz; ./.github/scripts/sjfz-build.sh)
      shell: bash
### check ucvm is still valid
    - name: check on ucvm
      run: (source $UCVM_INSTALL_PATH/conf/ucvm_env.sh; ucvm_query -H)
      shell: bash
    - name: test sjfz with ucvm
      run: (cd $RUNNER_WORKSPACE/sjfz/ucvm/work/model/sjfz; source $UCVM_INSTALL_PATH/conf/ucvm_env.sh; ./.github/scripts/sjfz-test-ucvm.sh)
      shell: bash
    - name: test sjfz under ucvm
      run: (cd $RUNNER_WORKSPACE/sjfz/ucvm; source $UCVM_INSTALL_PATH/conf/ucvm_env.sh; ./.github/scripts/ucvm-test.sh)
      shell: bash

  sjfz-build-ucvm-mac:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
    - name: set UCVM_SRC_PATH 
      run: echo "UCVM_SRC_PATH=$RUNNER_WORKSPACE/sjfz/ucvm" >> $GITHUB_ENV
    - name: set UCVM_INSTALL_PATH 
      run: echo "UCVM_INSTALL_PATH=$RUNNER_WORKSPACE/sjfz/target" >> $GITHUB_ENV
### build ucvm(main) first 
    - name: get-ucvm 
      uses: actions/checkout@v2
      with: 
        repository: 'SCECcode/UCVM'
##        ref: main
        ref: testMei
        path: ucvm
    - id: build-ucvm
      name: build ucvm
      uses: ./ucvm/.github/actions/build-ucvm-action
      with:
         initiating-repo: 'sjfz'
         target-model: 'sjfz'
         target-branch: 'testMei'
    - name: get-result ${{ steps.build-ucvm.outputs.build-log }}
      run: more ${{ steps.build-ucvm.outputs.build-log }}
      shell: bash
    - name: move stock sjfz away
      run: (rm -rf $RUNNER_WORKSPACE/sjfz/ucvm/work/model/sjfz)
      shell: bash
### build sjfz from github 
    - name: checkout sjfz main
      uses: actions/checkout@v2
      with: 
        path: sjfz
    - name: move it to the right location
      run: (mv sjfz $RUNNER_WORKSPACE/sjfz/ucvm/work/model; pwd; ls)
      shell: bash
    - name: build sjfz as part of ucvm 
      run: (cd $RUNNER_WORKSPACE/sjfz/ucvm/work/model/sjfz; ./.github/scripts/sjfz-build.sh)
      shell: bash
### check ucvm is still valid
    - name: check on ucvm
      run: (source $UCVM_INSTALL_PATH/conf/ucvm_env.sh; ucvm_query -H)
      shell: bash
    - name: test sjfz with ucvm
      run: (cd $RUNNER_WORKSPACE/sjfz/ucvm/work/model/sjfz; source $UCVM_INSTALL_PATH/conf/ucvm_env.sh; ./.github/scripts/sjfz-test-ucvm.sh)
      shell: bash
    - name: test sjfz under ucvm
      run: (cd $RUNNER_WORKSPACE/sjfz/ucvm; source $UCVM_INSTALL_PATH/conf/ucvm_env.sh; ./.github/scripts/ucvm-test.sh)
      shell: bash





